name: Giphy Bullshit

on: 
  pull_request:
    types: [opened, edited]

jobs:
  giphy-generator: 
    runs-on: ubunut-latest

    steps:
    - name: GIPHY Generator
      uses: IAmHughes/giphy-generator@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
      with: 
        reating: 'g'
        lang: 'en'
